import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import path from 'path';
import settingsRoutes from './routes/settings';
import memberRoutes from './routes/members';
import projectRoutes from './routes/projects';
import sprintRoutes from './routes/sprints';
import storyRoutes from './routes/stories';
import leaveRoutes from './routes/leaves';
import dsuRoutes from './routes/dsus';
import analyticsRoutes from './routes/analytics';
import exportRoutes from './routes/export';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));
app.use('/api/settings', settingsRoutes);
app.use('/api/members', memberRoutes);
app.use('/api/projects', projectRoutes);
app.use('/api/sprints', sprintRoutes);
app.use('/api/stories', storyRoutes);
app.use('/api/leaves', leaveRoutes);
app.use('/api/dsus', dsuRoutes);
app.use('/api/analytics', analyticsRoutes);
app.use('/api/export', exportRoutes);
app.listen(3001, () => console.log('Server is running on port 3001'));